### ISSUE TITLE
Outlook Email Not Working

### ISSUE THREAD

**Issue by skrawani** [gbkel/kindlefy#1]
Outlook Mail's as sender email doens't work and results in connection timeout

**Comment by guilhermebkel** [comment]
Hello @skrawani! Thanks for reporting and making a fix for it! I'll give a look at it and so I'll merge in case everything is fine :)

**Comment by guilhermebkel** [comment]
Thanks, merged in production! https://github.com/gbkel/kindlefy/commit/dba65ab8b557f39c28449924a0c6ae73f4e8f641 :)
